[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021C3C9E58E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/0b7af9a0b9a796aefc6e4812ce4ab9ed
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021C3C9E4FB0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/0b7af9a0b9a796aefc6e4812ce4ab9ed
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021C3C9E5280>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/0b7af9a0b9a796aefc6e4812ce4ab9ed