[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021C3BDAAED0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/6c932b5b-ef4f-40db-81ff-b1d198359beb
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021C3C946C90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/6c932b5b-ef4f-40db-81ff-b1d198359beb
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021C3C945B50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/6c932b5b-ef4f-40db-81ff-b1d198359beb